export const CONDITIONS_D = [
  "DACRIOCISTITE", "DEGENERAZIONE MACULARE SENILE", "DEMENZA SENILE",
  "DEMENZA VASCOLARE", "DENGUE", "DEPRESSIONE", "DEPRESSIONE POST PARTUM",
  "DERMATITE", "DERMATITE ATOPICA", "DERMATITE DA PANNOLINO",
  "DERMATITE PERIORALE", "DERMATITE SEBORROICA", "DERMATOFIBROMA",
  "DERMATOFITOSI", "DIABETE", "DIABETE GESTAZIONALE", "DIABETE INSIPIDO",
  "DIARREA DEL VIAGGIATORE", "DIFETTO INTERATRIALE", "DIFTERITE", "DISIDROSI",
  "DISLESSIA", "DISLIPIDEMIE", "DISPRASSIA", "DISTACCO DI RETINA", "DISTIMIA",
  "DISTORSIONE", "DISTORSIONE DELLA CAVIGLIA", "DISTRESS RESPIRATORIO",
  "DISTROFIA DI DUCHENNE", "DISTURBI DELLA COAGULAZIONE", "DISTURBO BIPOLARE",
  "DISTURBO CICLOTIMICO", "DISTURBO DA ALIMENTAZIONE INCONTROLLATA",
  "DISTURBO DI PERSONALITA' BORDERLINE", "DISTURBO EVITANTE DI PERSONALITA'",
  "DISTURBO NARCISISTICO DI PERSONALITA'", "DISTURBO OSSESSIVO COMPULSIVO",
  "DISTURBO POST TRAUMATICO DA STRESS", "DITO A SCATTO", "DIVERTICOLI ESOFAGEI",
  "DIVERTICOLITE", "DIVERTICOLO DI MECKEL", "DIVERTICOLO DI ZENKER",
  "DIVERTICOLOSI", "DREPANOCITOSI", "DUODENITE"
];