export const CONDITIONS_A = [
  "ACALASIA", "ACETONEMIA", "ACIDOSI METABOLICA", "ACNE", "ACONDROPLASIA",
  "ACROMEGALIA", "ADENOIDI IPERTROFICHE", "ADENOIDITE", "AIDS", "ALBINISMO",
  "ALCOLISMO", "ALGODISTROFIA", "ALLERGIA ALIMENTARE", "ALLERGIA AL NICHEL e SNAS",
  "ALLERGIA AL LATTOSIO", "ALLERGIA DA CONTATTO", "ALLERGIE RESPIRATORIE",
  "ALLUCE VALGO", "ALOPECIA AREATA", "AMBLIOPIA", "AMEBIASI", "AMILOIDOSI",
  "ANAFILASSI", "ANEMIA", "ANEMIA DI FANCONI", "ANEMIA EMOLITICA",
  "ANEURISMA AORTICO", "ANEURISMA CEREBRALE", "ANGINA ADDOMINALE",
  "ANGINA INSTABILE", "ANGINA PECTORIS", "ANGIODISPLASIA", "ANGIOMA",
  "ANISAKIASI", "ANORESSIA", "ANSIA", "ANTRACE", "APNEA NOTTURNA",
  "APPENDICITE", "ARRESTO CARDIACO", "ARTERITE A CELLULE GIGANTI", "ARTRITE",
  "ARTRITE GOTTOSA", "ARTRITE IDIOPATICA GIOVANILE", "ARTRITE PSORIASICA",
  "ARTRITE REATTIVA", "ARTRITE REUMATOIDE", "ARTROSI", "ARTROSI DELLE MANI",
  "ARTROSI CERVICALE", "ASBESTOSI", "ASCESSO GENGIVALE", "ASCESSO PERIANALE",
  "ASCESSO POLMONARE", "ASMA", "ASPERGILLOSI", "ASTIGMATISMO", "ATEROSCLEROSI",
  "ATRESIA ESOFAGEA", "ATROFIA MUSCOLARE SPINALE", "ATTACCO DI ANSIA",
  "ATTACCO DI PANICO", "ATTACCO ISCHEMICO TRANSITORIO", "AUTISMO"
];