export const CONDITIONS_B = [
  "BABESIOSI", "BALANOPOSTITE", "BERIBERI", "BINGE DRINKING", "BLEFARITE",
  "BORSITE", "BOTULISMO", "BPCO", "BRONCHIECTASIE", "BRONCHIOLITE",
  "BRONCHITE", "BRUCELLOSI", "BRUXISMO", "BULIMIA"
];