export const CONDITIONS_M = [
  "MALARIA", "MALATTIA DA GRAFFIO DI GATTO", "MALATTIA DI CHAGAS",
  "MALATTIA DI CREUTZFELDT - JAKOB", "MALATTIA DI GAUCHER", "MALATTIA DI HUNTINGTON",
  "MALATTIA DI KAWASAKI", "MALATTIA DI LYME", "MALATTIA DI PAGET DEL CAPEZZOLO",
  "MALATTIA DI PEYRONIE", "MALATTIA DI VON WILLEBRAND", "MALATTIA DI WHIPPLE",
  "MALATTIA DI WILSON", "MALATTIA INFIAMMATORIA PELVICA", "MALATTIA MANI PIEDI BOCCA",
  "MASTITE", "MASTOIDITE", "MEGACOLON TOSSICO", "MELANOMA", "MELIOIDOSI", "MENINGIOMA",
  "MENINGITE", "MENOPAUSA", "MESOTELIOMA PLEURICO", "MIASTENIA GRAVIS", "MIELITE",
  "MIELOFIBROSI", "MIELOMA MULTIPLO", "MIELOPATIA", "MILIARIA", "MIOCARDITE",
  "MIOPIA", "MIRINGITE", "MIXOMA", "MOLLUSCO CONTAGIOSO", "MONONUCLEOSI", "MORBILLO",
  "MORBO DI ADDISON", "MORBO DI ALZHEIMER", "MORBO DI BOWEN", "MORBO DI COOLEY",
  "MORBO DI CROHN", "MORBO DI CUSHING", "MORBO DI DUPUYTREN",
  "MORBO DI GRAVES - BASEDOW", "MORBO DI HASHIMOTO (TIROIDITE)",
  "MORBO DI HIRSCHSPRUNG", "MORBO DI PAGET", "MORBO DI PARKINSON",
  "MORBO DI SCHEUERMANN"
];

export const CONDITIONS_N = [
  "NARCOLESSIA", "NEFRITE", "NEFROPATIA DIABETICA", "NEURINOMA DELL'ACUSTICO",
  "NEURITE OTTICA", "NEUROBLASTOMA", "NEUROFRIBROMATOSI", "NEUROMA DI MORTON",
  "NEURONITE VESTIBOLARE", "NEUROPATIA DIABETICA", "NEVI (NEO - NEI)",
  "NEVO DI SPITZ", "NODULO DELLA TIROIDE"
];

export const CONDITIONS_O = [
  "OBESITA'", "OCCHIO DI PERNICE", "OCCLUSIONE INTESTINALE", "ONFALITE",
  "ONICOFAGIA", "ONICOMICOSI", "ORCHITE", "ORZAIOLO", "OSSIURIASI", "OSTEITE",
  "OSTEOCONDRITE", "OSTEOCONDROSI", "OSTEOGENESI IMPERFETTA", "OSTEOMA OSTEOIDE",
  "OSTEOMIELITE", "OSTEONECROSI", "OSTEOPENIA", "OSTEOPETROSI", "OSTEOPOROSI",
  "OSTEOSARCOMA", "OSTRUZIONE INTESTINALE", "OTITE", "OTITE ACUTA",
  "OTITE BAROTRAUMATICA", "OTITE BOLLOSA", "OTITE MEDIA", "OTOSCLEROSI", "OVULAZIONE"
];

export const CONDITIONS_P = [
  "PALATOSCHISI", "PANCREATITE", "PANCREATITE ACUTA", "PANNICOLITE", "PARAFIMOSI",
  "PARALISI CEREBRALE INFANTILE", "PARAPARESI SPASTICA", "PARODONTITE", "PARONICHIA",
  "PAROTITE", "PATERECCIO", "PEDICULOSI", "PELLAGRA", "PEMFIGO VOLGARE",
  "PEMFIGOIDE BOLLOSO", "PEMFIGOIDE GESTAZIONALE", "PERICARDITE", "PERITONITE",
  "PERTOSSE", "PFAPA", "PIEDE CAVO", "PIEDE D'ATLETA", "PIEDE DIABETICO",
  "PIEDE PIATTO", "PIELONEFRITE", "PINGUECOLA", "PITIRIASI ALBA", "PITIRIASI ROSEA",
  "PLACENTA ACCRETA", "PLACENTA PREVIA", "PLEURITE", "POLICITEMIA VERA",
  "POLIDIPSIA PSICOGENA", "POLIMIALGIA REUMATICA", "POLIMIOSITE", "POLIOMIELITE",
  "POLIPI INTESTINALI", "POLIPI UTERINI", "POLIPOSI NASALE (POLIPI NASO)",
  "POLMONITE", "POLMONITE AB INGESTIS", "PORFIRIA", "PORFIRIA CUTANEA TARDA",
  "PRE - ECLAMPSIA", "PRESBIOPIA", "PROCTITE", "PROGERIA", "PROSTATITE",
  "PSICOSI DI KORSAKOFF", "PSORIASI", "PUBALGIA", "PULPITE"
];

export const CONDITIONS_R = [
  "RABBIA", "RADICOLOPATIA", "RAFFREDDORE", "RAGADE ANALE (ragadi anali)",
  "REFLUSSO GASTROESOFAGEO", "RETINITE PIGMENTOSA", "RETINOBLASTOMA",
  "RETINOPATIA DIABETICA", "RINITE", "RINITE ALLERGICA", "RIZOARTROSI",
  "ROSACEA", "ROSOLIA"
];
