export const CONDITIONS_S = [
  "SACROILEITE", "SALMONELLA", "SALPINGITE", "SARCOMA DI KAPOSI", "SCABBIA",
  "SCARLATTINA", "SCHISTOSOMIASI", "SCHIZOFRENIA", "SCIALOADENITE", "SCLERITE",
  "SCLERODERMIA", "SCLEROSI LATERALE AMIOTROFICA", "SCLEROSI MULTIPLA",
  "SCLEROSI TUBEROSA", "SCORBUTO", "SEPSI", "SESTA MALATTIA", "SFEROCITOSI",
  "SHIGELLOSI", "SHOCK SETTICO", "SIFILIDE", "SILICOSI", "SINDROME COMPARTIMENTALE",
  "SINDROME DA ASPIRAZIONE DI MECONIO", "SINDROME DA COLON IRRITABILE",
  "SINDROME DA DECOMPRESSIONE", "SINDROME DA DEFICIT DI ATTENZIONE E IPERATTIVITA' (ADHD)",
  "SINDROME DA STANCHEZZA CRONICA", "SINDROME DA PIRIFORME",
  "SINDROME DEL TUNNEL CARPALE", "SINDROME INTESTINO IRRITABILE",
  "SINDROME DELL'OCCHIO SECCO", "SINDROME DELL'OVAIO POLICISTICO",
  "SINDROME DELLA BOCCA URENTE", "SINDROME DELLA CAUDA EQUINA",
  "SINDROME DELLE GAMBE SENZA RIPOSO", "SINDROME DELLO STRETTO TORACICO",
  "SINDROME DI ASPERGER", "SINDROME DI BRUGADA", "SINDROME DI DE QUERVAIN",
  "SINDROME DI DOWN", "SINDROME DI EHLERS - DANLOS", "SINDROME DI FANCONI",
  "SINDROME DI HORNER", "SINDROME DI KLINEFELTER", "SINDROME DI MALLORY - WEISS",
  "SINDROME DI MARFAN", "SINDROME DI MENIERE", "SINDROME DI PICKWICK",
  "SINDROME DI PRADER - WILLI", "SINDROME DI REITER", "SINDROME DI REYE",
  "SINDROME DI SJOGREN", "SINDROME DI TOURETTE", "SINDROME DI TURNER",
  "SINDROME DI ZOLLINGER - ELLISON", "SINDROME EMOTILICO - UREMICA",
  "SINDROME FETO - ALCOLICA", "SINDROME FIBROMIALGICA (FIBROMIALGIA)",
  "SINDROME METABOLICA", "SINDROME PREMESTRUALE", "SINDROME SEROTONINERGICA",
  "SINDROME PARAINFLUENZALE", "SINOVITE", "SINTOMI DELLO SCOMPENSO CARDIACO",
  "SINTOMI GANGLI (O CISTI SINOVIALI)", "SINUSITE", "SIRINGOMIELIA",
  "SPALLA CONGELATA", "SPASMO ESOFAGEO", "SPERONE CALCANEARE", "SPINA BIFIDA",
  "SPINA CALCANEARE", "SPONDILITE ANCHILOSANTE", "SPONDILOSISTESI",
  "SPONDILOSI CERCIVALE", "SPRUE TROPICALE", "STEATOSI EPATICA",
  "STEATOSI EPATICA NON ALCOLICA", "STENOSI CERVICALE", "STENOSI LOMBARE",
  "STENOSI PILORICA", "STENOSI SPINALE", "STENOSI URETRALE", "STIRAMENTO MUSCOLARE",
  "STITICHEZZA", "STRABISMO", "STRAPPO MUSCOLARE"
];

export const CONDITIONS_T = [
  "TALASSEMIA", "TALLONITE", "TENDINITE", "TENOSINOVITE", "TETANO", "TIFO",
  "TIMOMA", "TINEA CAPITIS", "TINEA VERSICOLOR", "TIROIDITE SUBACUTA", "TONSILLITE",
  "TORSIONE ANNESSIALE", "TORSIONE TESTICOLARE", "TOXOPLASMOSI", "TRACHEITE",
  "TRACOMA", "TRICHINOSI", "TRICHOMONAS", "TRIPANOSOMIASI AFRICANA", "TRISOMIA 13",
  "TRISOMIA 18", "TROMBOCITEMIA ESSENZIALE", "TROMBOFILIA", "TROMBOFLEBITE",
  "TROMBOSI VENOSA PROFONDA", "TROMBOSI VENOSA SUPERFICIALE", "TUBERCOLOSI",
  "TUMORE AI TESTICOLI (cancro)", "TUMORE AL FEGATO (cancro)",
  "TUMORE AL PANCREAS (cancro)", "TUMORE AL POLMONE (cancro)",
  "TUMORE AL RENE (cancro)", "TUMORE ALLA PROSTATA (cancro)",
  "TUMORE ALLO STOMACO (cancro)", "TUMORE DEL COLON RETTO (cancro)",
  "TUMORE DEL PENE (cancro)", "TUMORE DELL'ANO (cancro)",
  "TUMORE DELL'ESOFAGO (cancro)", "TUMORE DELL'OVAIO (cancro)",
  "TUMORE DELL'URETRA (cancro)", "TUMORE DELLA TIROIDE (cancro)",
  "TUMORE DELLE GHIANDOLE SALIVARI (cancro)", "TUMORE DI WILMS (cancro)",
  "TUMORE CARDIACO (cancro)", "TUMORE DEL MIDOLLO SPINALE (cancro)",
  "TUMORE DELLA LARINGE (cancro)", "TUMORE IPOFISI (cancro)"
];

export const CONDITIONS_U = [
  "ULCERA CORNEALE", "ULCERA DUODENALE", "ULCERA GASTRICA", "ULCERA PEPTICA",
  "UNGHIA INCARNITA", "URETRITE", "USTIONE", "UVEITE"
];

export const CONDITIONS_V = [
  "VAGINITE", "VAGINOSI BATTERICA", "VAIOLO", "VARICELLA", "VARICI ESOFAGEE",
  "VARICOCELE", "VENE VARICOSE", "VERRUCHE", "VESCICA NEUROLOGICA",
  "VIRUS ZIKA", "VITILIGINE"
];

export const CONDITIONS_Z = [
  "ZAFFAMENTO", "ZAHN (MALATTIA DI)", "ZIEVE (SINDROME DI)", "ZIGOMICOSI",
  "ZOANTROPIA"
];
