export const CONDITIONS_E = [
  "EBOLA", "ECHINOCOCCOSI", "ECTASIA DUTTALE", "EDEMA CEREBRALE",
  "EDEMA POLMONARE", "EMBOLIA", "EMBOLIA ARTERIOSA", "EMBOLIA POLMONARE",
  "EMICRANIA", "EMOCROMATOSI", "EMOCROMATOSI PRIMITIVA E SECONDARIA",
  "EMOFILIA", "EMOGLOBINURIA PAROSSISTICA NOTTURNA", "EMORRAGIA CEREBRALE",
  "EMORROIDI", "EMOSIDEROSI", "ENCEFALITE", "ENCEFALITE DA ZECCA (TBE)",
  "ENCEFALITE GIAPPONESE", "ENCEFALOPATIA DI WERNICKE", "ENCONDROMA",
  "ENDOCARDITE INFETTIVA", "ENDOCARDITE NON INFETTIVA", "ENDOMETRIOSI",
  "ENFISEMA", "ENTERITE", "ENTESITE", "EPATITE", "EPATITE A", "EPATITE B",
  "EPATITE C", "EPATITE D", "EPATITE E", "EPATITE FULMINANTE", "EPICONDILITE",
  "EPIDERMODISPLASIA VERRUCIFORME", "EPIDERMOLISI BOLLOSA", "EPIDIDIMITE",
  "EPISCLERITE", "EPITROCLEITE", "EPULIDE", "ERISIPELA", "ERITEMA MULTIFORME",
  "ERITEMA SOLARE", "ERITRASMA", "ERITROBLASTOSI FETALE", "ERNIA ADDOMINALE",
  "ERNIA DEL DISCO", "ERNIA IATALE", "ERNIA INGUINALE", "ESOFAGITE",
  "ESOFAGO DI BARRET"
];

export const CONDITIONS_F = [
  "FARINGITE", "FARINGITE CRONICA", "FARINGOTONSILLITE", "FASCITE PLANTARE",
  "FAVISMO", "FEBBRE", "FEBBRE DI LASSA", "FEBBRE EMORRAGICA CRIMEA - CONGO",
  "FEBBRE EMORRAGICA DI MARBURG", "FEBBRE GIALLA", "FEBBRE REUMATICA",
  "FEOCROMOCITOMA", "FIBRILLAZIONE ATRIALE",
  "FIBRODISPLASIA OSSIFICANTE PROGRESSIVA", "FIBROMA MAMMARIO",
];

export const CONDITIONS_G = [
  "GASTRITE", "GASTROENTERITE", "GASTROENTERITE VIRALE", "GELONI", "GENGIVITE",
  "GIARDIASI", "GINOCCHIO VALGO", "GINOCCHIO VARO", "GIRADITO", "GLAUCOMA",
];

export const CONDITIONS_H = [
  "HERPES GENITALE", "HERPES SIMPLEX", "HERPES ZOSTER OFTALMICO",
  "HERPES ZOSTER", "HIV"
];

export const CONDITIONS_I = [
  "ICTUS", "IDROCEFALO", "IDROCEFALO NORMOTESO", "IDROCELE", "IDRONEFROSI",
  "IMPETIGINE", "INDIGESTIONE", "INFARTO CARDIACO", "INFARTO INTESTINALE",
  "INFARTO MIOCARDICO", "INFARTO POLMONARE", "INFEZIONE DA CYTOMEGALOVIRUS (CMV)",
  "INFEZIONE DA VIRUS WEST NILE", "INFIAMMAZIONE DEL NERVO TRIGEMINO",
  "INFIAMMAZIONE TENDINE D'ACHILLE", "INFLUENZA", "INDIGESTIONE DI SOSTANZE CAUSTICHE",
  "INSUFFICIENZA CARDIACA", "INSUFFICIENZA RENALE", "INSUFFICIENZA RESPIRATORIA",
  "INSUFFICIENZA SURRENALICA", "INSULINEMIA", "INSULINOMA", "INTERTRIGINE",
  "INTOLLERANZA ALL'ISTAMINA", "INTOLLERANZA AL GLUTINE", "INTOLLERANZA AL LATTOSIO",
  "INTOLLERANZA AL NICHEL", "INTOLLERANZE ALIMENTARI",
  "INTOSSICAZIONE DA MONOSSIDO DI CARBONIO", "IPEREMESI GRAVIDICA", "IPERMETROPIA",
  "IPERPARATIROIDISMO", "IPERTENSIONE", "IPERTENSIONE POLMONARE",
  "IPERTERMIA MALIGNA", "IPERTIROIDISMO", "IPERTROFIA DEI TURBINATI",
  "IPERTROFIA PROSTRATICA BENIGNA", "IPERTROFIA VENTRICOLARE", "IPOCONDRIA",
  "IPOGONADISMO MASCHILE", "IPOPARATIROIDISMO", "IPOTIROIDISMO", "IRIDOCICLITE",
  "ISCHEMIA CEREBRALE", "ISTOPLASMOSI", "ITTERO", "ITTIOSI"
];

export const CONDITIONS_L = [
  "LABBRO LEPORINO", "LABIRINTITE", "LARINGITE", "LEBBRA", "LEGIONELLOSI (LEGIONELLA)",
  "LEISHMANIOSI", "LEPTOSPIROSI", "LEUCEMIA", "LICHEN PLANUS", "LICHEN SIMPLEX",
  "LINFOGRANULOMA VENEREO", "LINFOMA", "LINFOMA DI HODGKIN", "LINFOMA NON HODGKIN",
  "LIPOMA", "LIPOSARCOMA", "LISTERIOSI", "LUPUS ERIMATOSO SISTEMICO", "LUSSAZIONE"
];
