import { CONDITIONS_A } from './lists/conditions-a';
import { CONDITIONS_B } from './lists/conditions-b';
import { CONDITIONS_C } from './lists/conditions-c';
import { CONDITIONS_D } from './lists/conditions-d';
import {
  CONDITIONS_E, CONDITIONS_F, CONDITIONS_G, CONDITIONS_H,
  CONDITIONS_I, CONDITIONS_L, CONDITIONS_M, CONDITIONS_N,
  CONDITIONS_O, CONDITIONS_P, CONDITIONS_R, CONDITIONS_S,
  CONDITIONS_T, CONDITIONS_U, CONDITIONS_V, CONDITIONS_Z
} from './conditions-e-l';

export {
  CONDITIONS_A,
  CONDITIONS_B,
  CONDITIONS_C,
  CONDITIONS_D,
  CONDITIONS_E,
  CONDITIONS_F,
  CONDITIONS_G,
  CONDITIONS_H,
  CONDITIONS_I,
  CONDITIONS_L,
  CONDITIONS_M,
  CONDITIONS_N,
  CONDITIONS_O,
  CONDITIONS_P,
  CONDITIONS_R,
  CONDITIONS_S,
  CONDITIONS_T,
  CONDITIONS_U,
  CONDITIONS_V,
  CONDITIONS_Z
};