export const CONDITIONS_A = [
  "ACALASIA", "ACETONEMIA", "ACIDOSI METABOLICA", "ACNE", "ACONDROPLASIA",
  "ACROMEGALIA", "ADENOIDI IPERTROFICHE", "ADENOIDITE", "AIDS", "ALBINISMO",
  "ALCOLISMO", "ALGODISTROFIA", "ALLERGIA ALIMENTARE", "ALLERGIA AL NICHEL e SNAS",
  "ALLERGIA AL LATTOSIO", "ALLERGIA DA CONTATTO", "ALLERGIE RESPIRATORIE",
  "ALLUCE VALGO", "ALOPECIA AREATA", "AMBLIOPIA", "AMEBIASI", "AMILOIDOSI",
  "ANAFILASSI", "ANEMIA", "ANEMIA DI FANCONI", "ANEMIA EMOLITICA",
  "ANEURISMA AORTICO", "ANEURISMA CEREBRALE", "ANGINA ADDOMINALE",
  "ANGINA INSTABILE", "ANGINA PECTORIS", "ANGIODISPLASIA", "ANGIOMA",
  "ANISAKIASI", "ANORESSIA", "ANSIA", "ANTRACE", "APNEA NOTTURNA",
  "APPENDICITE", "ARRESTO CARDIACO", "ARTERITE A CELLULE GIGANTI", "ARTRITE",
  "ARTRITE GOTTOSA", "ARTRITE IDIOPATICA GIOVANILE", "ARTRITE PSORIASICA",
  "ARTRITE REATTIVA", "ARTRITE REUMATOIDE", "ARTROSI", "ARTROSI DELLE MANI",
  "ARTROSI CERVICALE", "ASBESTOSI", "ASCESSO GENGIVALE", "ASCESSO PERIANALE",
  "ASCESSO POLMONARE", "ASMA", "ASPERGILLOSI", "ASTIGMATISMO", "ATEROSCLEROSI",
  "ATRESIA ESOFAGEA", "ATROFIA MUSCOLARE SPINALE", "ATTACCO DI ANSIA",
  "ATTACCO DI PANICO", "ATTACCO ISCHEMICO TRANSITORIO", "AUTISMO"
];

export const CONDITIONS_B = [
  "BABESIOSI", "BALANOPOSTITE", "BERIBERI", "BINGE DRINKING", "BLEFARITE",
  "BORSITE", "BOTULISMO", "BPCO", "BRONCHIECTASIE", "BRONCHIOLITE",
  "BRONCHITE", "BRUCELLOSI", "BRUXISMO", "BULIMIA"
];

export const CONDITIONS_C = [
  "CALAZIO", "CALCOLI AL FEGATO", "CALCOLI ALLA CISTIFELLEA", "CALCOLI RENALI",
  "CALCOLI TONSILLARI", "CALCOLOSI SALIVARE", "CALCOLOSI RENALE",
  "CANCRO AL COLLO DELL'UTERO (TUMORE)", "CANCRO AL COLON (TUMORE)",
  "CANCRO AL SENO (TUMORE)", "CANCRO ALLA PROSTATA (TUMORE)",
  "CANCRO ALL'ENDOMETRIO (TUMORE)", "CANCRO DELLA VESCICA (TUMORE)", "CANCROIDE",
  "CANDIDA", "CARCINOMA BASO-CELLULARE (BASALIOMA)",
  "CARCINOMA DELLA CERVICE UTERINA", "CARCINOMA SQUAMO - CELLULARE", "CARIE",
  "CARATATTA", "CEFALEA", "CELIACHIA", "CELLULITE", "CELLULITE INFETTIVA",
  "CERVICITE", "CHELOIDE", "CHERATITE DA HERPES SIMPLEX", "CHERATOCONO",
  "CHERATOSI ATTINICA", "CHETOACIDOSI ALCOLICA", "CHETOACIDOSI DIABETICA",
  "CHIKUNGUNYA", "CINETOSI", "CIRROSI BILIARE", "CIRROSI EPATICA",
  "CISTI DERMOIDE", "CISTI DI BAKER", "CISTI DI BARTOLINI", "CISTI OVARICA",
  "CISTICERCOSI", "CISTINURIA", "CISTITE", "CISTITE INTERSTIZIALE",
  "CISTOPIELITE", "CITOMEGALOVIRUS", "CLAMIDIA", "CLAUDICATIO INTERMITTENS",
  "COAGULAZIONE INTRAVASCOLARE DISSEMINATA", "COGGIGODINIA",
  "COLANGIOCARCINOMA", "COLANGITE SCLEROSANTE", "COLECISTITE",
  "COLECISTITE ALITIASICA", "COLELITIASI o CALCOLI BILIARI",
  "COLERA", "COLICA RENALE", "COLITE", "COLITE ISCHEMICA", "COLITE SPASTICA",
  "COLITE ULCEROSA", "COLPO DELLA STREGA", "COLPO DI CALORE",
  "COLPO DI FRUSTA CERVICALE", "CONDILOMA", "CONDROCALCINOSI", "CONDROMA",
  "CONDROMALACIA", "CONDROSARCOMA", "CONGELAMENTO", "CONGESTIONE DIGESTIVA",
  "CONGIUNTIVITE", "CONTRATTURA MUSCOLARE", "CORONOPATIA",
  "CORPO LUTEO EMORRAGICO", "COUPEROSE", "COVID 19 (CORONAVIRUS)",
  "CRIOGLOBULINEMIA", "CRIPTOCOCCOSI", "CROUP", "CUORE POLMONARE"
];

export const CONDITIONS_D = [
  "DACRIOCISTITE", "DEGENERAZIONE MACULARE SENILE", "DEMENZA SENILE",
  "DEMENZA VASCOLARE", "DENGUE", "DEPRESSIONE", "DEPRESSIONE POST PARTUM",
  "DERMATITE", "DERMATITE ATOPICA", "DERMATITE DA PANNOLINO",
  "DERMATITE PERIORALE", "DERMATITE SEBORROICA", "DERMATOFIBROMA",
  "DERMATOFITOSI", "DIABETE", "DIABETE GESTAZIONALE", "DIABETE INSIPIDO",
  "DIARREA DEL VIAGGIATORE", "DIFETTO INTERATRIALE", "DIFTERITE", "DISIDROSI",
  "DISLESSIA", "DISLIPIDEMIE", "DISPRASSIA", "DISTACCO DI RETINA", "DISTIMIA",
  "DISTORSIONE", "DISTORSIONE DELLA CAVIGLIA", "DISTRESS RESPIRATORIO",
  "DISTROFIA DI DUCHENNE", "DISTURBI DELLA COAGULAZIONE", "DISTURBO BIPOLARE",
  "DISTURBO CICLOTIMICO", "DISTURBO DA ALIMENTAZIONE INCONTROLLATA",
  "DISTURBO DI PERSONALITA' BORDERLINE", "DISTURBO EVITANTE DI PERSONALITA'",
  "DISTURBO NARCISISTICO DI PERSONALITA'", "DISTURBO OSSESSIVO COMPULSIVO",
  "DISTURBO POST TRAUMATICO DA STRESS", "DITO A SCATTO", "DIVERTICOLI ESOFAGEI",
  "DIVERTICOLITE", "DIVERTICOLO DI MECKEL", "DIVERTICOLO DI ZENKER",
  "DIVERTICOLOSI", "DREPANOCITOSI", "DUODENITE"
];

export const CONDITIONS_E = [
  "EBOLA", "ECHINOCOCCOSI", "ECTASIA DUTTALE", "EDEMA CEREBRALE",
  "EDEMA POLMONARE", "EMBOLIA", "EMBOLIA ARTERIOSA", "EMBOLIA POLMONARE",
  "EMICRANIA", "EMOCROMATOSI", "EMOCROMATOSI PRIMITIVA E SECONDARIA",
  "EMOFILIA", "EMOGLOBINURIA PAROSSISTICA NOTTURNA", "EMORRAGIA CEREBRALE",
  "EMORROIDI", "EMOSIDEROSI", "ENCEFALITE", "ENCEFALITE DA ZECCA (TBE)",
  "ENCEFALITE GIAPPONESE", "ENCEFALOPATIA DI WERNICKE", "ENCONDROMA",
  "ENDOCARDITE INFETTIVA", "ENDOCARDITE NON INFETTIVA", "ENDOMETRIOSI",
  "ENFISEMA", "ENTERITE", "ENTESITE", "EPATITE", "EPATITE A", "EPATITE B",
  "EPATITE C", "EPATITE D", "EPATITE E", "EPATITE FULMINANTE", "EPICONDILITE",
  "EPIDERMODISPLASIA VERRUCIFORME", "EPIDERMOLISI BOLLOSA", "EPIDIDIMITE",
  "EPISCLERITE", "EPITROCLEITE", "EPULIDE", "ERISIPELA", "ERITEMA MULTIFORME",
  "ERITEMA SOLARE", "ERITRASMA", "ERITROBLASTOSI FETALE", "ERNIA ADDOMINALE",
  "ERNIA DEL DISCO", "ERNIA IATALE", "ERNIA INGUINALE", "ESOFAGITE",
  "ESOFAGO DI BARRET"
];

export const CONDITIONS_F = [
  "FARINGITE", "FARINGITE CRONICA", "FARINGOTONSILLITE", "FASCITE PLANTARE",
  "FAVISMO", "FEBBRE", "FEBBRE DI LASSA", "FEBBRE EMORRAGICA CRIMEA - CONGO",
  "FEBBRE EMORRAGICA DI MARBURG", "FEBBRE GIALLA", "FEBBRE REUMATICA",
  "FEOCROMOCITOMA", "FIBRILLAZIONE ATRIALE",
  "FIBRODISPLASIA OSSIFICANTE PROGRESSIVA", "FIBROMA MAMMARIO",
  "FIBROMA PENDULO", "FIBROMA UTERINO", "FIBROSI CISTICA", "FIBROSI EPATICA",
  "FIBROSI POLMONARE", "FIBROTECOMA OVARICO", "FIMOSI", "FISTOLA ANALE",
  "FLUOROSI", "FOLLICOLITE", "FRATTURA", "FRATTURA DEL PENE",
  "FUNGHI DELLA PELLE", "FUOCO DI SANT'ANTONIO"
];

export const CONDITIONS_G = [
  "GASTRITE", "GASTROENTERITE", "GASTROENTERITE VIRALE", "GELONI", "GENGIVITE",
  "GIARDIASI", "GINOCCHIO VALGO", "GINOCCHIO VARO", "GIRADITO", "GLAUCOMA",
  "GONARTROSI", "GONORREA", "GOTTA", "GOZZO", "GOZZO TIROIDEO",
  "GRANULOMA ANULARE", "GRANULOMA PIOGENICO", "GRAVIDANZA",
  "GRAVIDANZA ECTOPICA"
];

export const CONDITIONS_H = [
  "HERPES GENITALE", "HERPES SIMPLEX", "HERPES ZOSTER OFTALMICO",
  "HERPES ZOSTER", "HIV"
];

export const CONDITIONS_I = [
  "ICTUS", "IDROCEFALO", "IDROCEFALO NORMOTESO", "IDROCELE", "IDRONEFROSI",
  "IMPETIGINE", "INDIGESTIONE", "INFARTO CARDIACO", "INFARTO INTESTINALE",
  "INFARTO MIOCARDICO", "INFARTO POLMONARE", "INFEZIONE DA CYTOMEGALOVIRUS (CMV)",
  "INFEZIONE DA VIRUS WEST NILE", "INFIAMMAZIONE DEL NERVO TRIGEMINO",
  "INFIAMMAZIONE TENDINE D'ACHILLE", "INFLUENZA", "INDIGESTIONE DI SOSTANZE CAUSTICHE",
  "INSUFFICIENZA CARDIACA", "INSUFFICIENZA RENALE", "INSUFFICIENZA RESPIRATORIA",
  "INSUFFICIENZA SURRENALICA", "INSULINEMIA", "INSULINOMA", "INTERTRIGINE",
  "INTOLLERANZA ALL'ISTAMINA", "INTOLLERANZA AL GLUTINE", "INTOLLERANZA AL LATTOSIO",
  "INTOLLERANZA AL NICHEL", "INTOLLERANZE ALIMENTARI",
  "INTOSSICAZIONE DA MONOSSIDO DI CARBONIO", "IPEREMESI GRAVIDICA", "IPERMETROPIA",
  "IPERPARATIROIDISMO", "IPERTENSIONE", "IPERTENSIONE POLMONARE",
  "IPERTERMIA MALIGNA", "IPERTIROIDISMO", "IPERTROFIA DEI TURBINATI",
  "IPERTROFIA PROSTRATICA BENIGNA", "IPERTROFIA VENTRICOLARE", "IPOCONDRIA",
  "IPOGONADISMO MASCHILE", "IPOPARATIROIDISMO", "IPOTIROIDISMO", "IRIDOCICLITE",
  "ISCHEMIA CEREBRALE", "ISTOPLASMOSI", "ITTERO", "ITTIOSI"
];

export const CONDITIONS_L = [
  "LABBRO LEPORINO", "LABIRINTITE", "LARINGITE", "LEBBRA", "LEGIONELLOSI (LEGIONELLA)",
  "LEISHMANIOSI", "LEPTOSPIROSI", "LEUCEMIA", "LICHEN PLANUS", "LICHEN SIMPLEX",
  "LINFOGRANULOMA VENEREO", "LINFOMA", "LINFOMA DI HODGKIN", "LINFOMA NON HODGKIN",
  "LIPOMA", "LIPOSARCOMA", "LISTERIOSI", "LUPUS ERIMATOSO SISTEMICO", "LUSSAZIONE"
];

export const CONDITIONS_M = [
  "MALARIA", "MALATTIA DA GRAFFIO DI GATTO", "MALATTIA DI CHAGAS",
  "MALATTIA DI CREUTZFELDT - JAKOB", "MALATTIA DI GAUCHER", "MALATTIA DI HUNTINGTON",
  "MALATTIA DI KAWASAKI", "MALATTIA DI LYME", "MALATTIA DI PAGET DEL CAPEZZOLO",
  "MALATTIA DI PEYRONIE", "MALATTIA DI VON WILLEBRAND", "MALATTIA DI WHIPPLE",
  "MALATTIA DI WILSON", "MALATTIA INFIAMMATORIA PELVICA", "MALATTIA MANI PIEDI BOCCA",
  "MASTITE", "MASTOIDITE", "MEGACOLON TOSSICO", "MELANOMA", "MELIOIDOSI", "MENINGIOMA",
  "MENINGITE", "MENOPAUSA", "MESOTELIOMA PLEURICO", "MIASTENIA GRAVIS", "MIELITE",
  "MIELOFIBROSI", "MIELOMA MULTIPLO", "MIELOPATIA", "MILIARIA", "MIOCARDITE",
  "MIOPIA", "MIRINGITE", "MIXOMA", "MOLLUSCO CONTAGIOSO", "MONONUCLEOSI", "MORBILLO",
  "MORBO DI ADDISON", "MORBO DI ALZHEIMER", "MORBO DI BOWEN", "MORBO DI COOLEY",
  "MORBO DI CROHN", "MORBO DI CUSHING", "MORBO DI DUPUYTREN",
  "MORBO DI GRAVES - BASEDOW", "MORBO DI HASHIMOTO (TIROIDITE)",
  "MORBO DI HIRSCHSPRUNG", "MORBO DI PAGET", "MORBO DI PARKINSON",
  "MORBO DI SCHEUERMANN"
];

export const CONDITIONS_N = [
  "NARCOLESSIA", "NEFRITE", "NEFROPATIA DIABETICA", "NEURINOMA DELL'ACUSTICO",
  "NEURITE OTTICA", "NEUROBLASTOMA", "NEUROFRIBROMATOSI", "NEUROMA DI MORTON",
  "NEURONITE VESTIBOLARE", "NEUROPATIA DIABETICA", "NEVI (NEO - NEI)",
  "NEVO DI SPITZ", "NODULO DELLA TIROIDE"
];

export const CONDITIONS_O = [
  "OBESITA'", "OCCHIO DI PERNICE", "OCCLUSIONE INTESTINALE", "ONFALITE",
  "ONICOFAGIA", "ONICOMICOSI", "ORCHITE", "ORZAIOLO", "OSSIURIASI", "OSTEITE",
  "OSTEOCONDRITE", "OSTEOCONDROSI", "OSTEOGENESI IMPERFETTA", "OSTEOMA OSTEOIDE",
  "OSTEOMIELITE", "OSTEONECROSI", "OSTEOPENIA", "OSTEOPETROSI", "OSTEOPOROSI",
  "OSTEOSARCOMA", "OSTRUZIONE INTESTINALE", "OTITE", "OTITE ACUTA",
  "OTITE BAROTRAUMATICA", "OTITE BOLLOSA", "OTITE MEDIA", "OTOSCLEROSI", "OVULAZIONE"
];

export const CONDITIONS_P = [
  "PALATOSCHISI", "PANCREATITE", "PANCREATITE ACUTA", "PANNICOLITE", "PARAFIMOSI",
  "PARALISI CEREBRALE INFANTILE", "PARAPARESI SPASTICA", "PARODONTITE", "PARONICHIA",
  "PAROTITE", "PATERECCIO", "PEDICULOSI", "PELLAGRA", "PEMFIGO VOLGARE",
  "PEMFIGOIDE BOLLOSO", "PEMFIGOIDE GESTAZIONALE", "PERICARDITE", "PERITONITE",
  "PERTOSSE", "PFAPA", "PIEDE CAVO", "PIEDE D'ATLETA", "PIEDE DIABETICO",
  "PIEDE PIATTO", "PIELONEFRITE", "PINGUECOLA", "PITIRIASI ALBA", "PITIRIASI ROSEA",
  "PLACENTA ACCRETA", "PLACENTA PREVIA", "PLEURITE", "POLICITEMIA VERA",
  "POLIDIPSIA PSICOGENA", "POLIMIALGIA REUMATICA", "POLIMIOSITE", "POLIOMIELITE",
  "POLIPI INTESTINALI", "POLIPI UTERINI", "POLIPOSI NASALE (POLIPI NASO)",
  "POLMONITE", "POLMONITE AB INGESTIS", "PORFIRIA", "PORFIRIA CUTANEA TARDA",
  "PRE - ECLAMPSIA", "PRESBIOPIA", "PROCTITE", "PROGERIA", "PROSTATITE",
  "PSICOSI DI KORSAKOFF", "PSORIASI", "PUBALGIA", "PULPITE"
];

export const CONDITIONS_R = [
  "RABBIA", "RADICOLOPATIA", "RAFFREDDORE", "RAGADE ANALE (ragadi anali)",
  "REFLUSSO GASTROESOFAGEO", "RETINITE PIGMENTOSA", "RETINOBLASTOMA",
  "RETINOPATIA DIABETICA", "RINITE", "RINITE ALLERGICA", "RIZOARTROSI",
  "ROSACEA", "ROSOLIA"
];

export const CONDITIONS_S = [
  "SACROILEITE", "SALMONELLA", "SALPINGITE", "SARCOMA DI KAPOSI", "SCABBIA",
  "SCARLATTINA", "SCHISTOSOMIASI", "SCHIZOFRENIA", "SCIALOADENITE", "SCLERITE",
  "SCLERODERMIA", "SCLEROSI LATERALE AMIOTROFICA", "SCLEROSI MULTIPLA",
  "SCLEROSI TUBEROSA", "SCORBUTO", "SEPSI", "SESTA MALATTIA", "SFEROCITOSI",
  "SHIGELLOSI", "SHOCK SETTICO", "SIFILIDE", "SILICOSI", "SINDROME COMPARTIMENTALE",
  "SINDROME DA ASPIRAZIONE DI MECONIO", "SINDROME DA COLON IRRITABILE",
  "SINDROME DA DECOMPRESSIONE", "SINDROME DA DEFICIT DI ATTENZIONE E IPERATTIVITA' (ADHD)",
  "SINDROME DA STANCHEZZA CRONICA", "SINDROME DA PIRIFORME",
  "SINDROME DEL TUNNEL CARPALE", "SINDROME INTESTINO IRRITABILE",
  "SINDROME DELL'OCCHIO SECCO", "SINDROME DELL'OVAIO POLICISTICO",
  "SINDROME DELLA BOCCA URENTE", "SINDROME DELLA CAUDA EQUINA",
  "SINDROME DELLE GAMBE SENZA RIPOSO", "SINDROME DELLO STRETTO TORACICO",
  "SINDROME DI ASPERGER", "SINDROME DI BRUGADA", "SINDROME DI DE QUERVAIN",
  "SINDROME DI DOWN", "SINDROME DI EHLERS - DANLOS", "SINDROME DI FANCONI",
  "SINDROME DI HORNER", "SINDROME DI KLINEFELTER", "SINDROME DI MALLORY - WEISS",
  "SINDROME DI MARFAN", "SINDROME DI MENIERE", "SINDROME DI PICKWICK",
  "SINDROME DI PRADER - WILLI", "SINDROME DI REITER", "SINDROME DI REYE",
  "SINDROME DI SJOGREN", "SINDROME DI TOURETTE", "SINDROME DI TURNER",
  "SINDROME DI ZOLLINGER - ELLISON", "SINDROME EMOTILICO - UREMICA",
  "SINDROME FETO - ALCOLICA", "SINDROME FIBROMIALGICA (FIBROMIALGIA)",
  "SINDROME METABOLICA", "SINDROME PREMESTRUALE", "SINDROME SEROTONINERGICA",
  "SINDROME PARAINFLUENZALE", "SINOVITE", "SINTOMI DELLO SCOMPENSO CARDIACO",
  "SINTOMI GANGLI (O CISTI SINOVIALI)", "SINUSITE", "SIRINGOMIELIA",
  "SPALLA CONGELATA", "SPASMO ESOFAGEO", "SPERONE CALCANEARE", "SPINA BIFIDA",
  "SPINA CALCANEARE", "SPONDILITE ANCHILOSANTE", "SPONDILOSISTESI",
  "SPONDILOSI CERCIVALE", "SPRUE TROPICALE", "STEATOSI EPATICA",
  "STEATOSI EPATICA NON ALCOLICA", "STENOSI CERVICALE", "STENOSI LOMBARE",
  "STENOSI PILORICA", "STENOSI SPINALE", "STENOSI URETRALE", "STIRAMENTO MUSCOLARE",
  "STITICHEZZA", "STRABISMO", "STRAPPO MUSCOLARE"
];

export const CONDITIONS_T = [
  "TALASSEMIA", "TALLONITE", "TENDINITE", "TENOSINOVITE", "TETANO", "TIFO",
  "TIMOMA", "TINEA CAPITIS", "TINEA VERSICOLOR", "TIROIDITE SUBACUTA", "TONSILLITE",
  "TORSIONE ANNESSIALE", "TORSIONE TESTICOLARE", "TOXOPLASMOSI", "TRACHEITE",
  "TRACOMA", "TRICHINOSI", "TRICHOMONAS", "TRIPANOSOMIASI AFRICANA", "TRISOMIA 13",
  "TRISOMIA 18", "TROMBOCITEMIA ESSENZIALE", "TROMBOFILIA", "TROMBOFLEBITE",
  "TROMBOSI VENOSA PROFONDA", "TROMBOSI VENOSA SUPERFICIALE", "TUBERCOLOSI",
  "TUMORE AI TESTICOLI (cancro)", "TUMORE AL FEGATO (cancro)",
  "TUMORE AL PANCREAS (cancro)", "TUMORE AL POLMONE (cancro)",
  "TUMORE AL RENE (cancro)", "TUMORE ALLA PROSTATA (cancro)",
  "TUMORE ALLO STOMACO (cancro)", "TUMORE DEL COLON RETTO (cancro)",
  "TUMORE DEL PENE (cancro)", "TUMORE DELL'ANO (cancro)",
  "TUMORE DELL'ESOFAGO (cancro)", "TUMORE DELL'OVAIO (cancro)",
  "TUMORE DELL'URETRA (cancro)", "TUMORE DELLA TIROIDE (cancro)",
  "TUMORE DELLE GHIANDOLE SALIVARI (cancro)", "TUMORE DI WILMS (cancro)",
  "TUMORE CARDIACO (cancro)", "TUMORE DEL MIDOLLO SPINALE (cancro)",
  "TUMORE DELLA LARINGE (cancro)", "TUMORE IPOFISI (cancro)"
];

export const CONDITIONS_U = [
  "ULCERA CORNEALE", "ULCERA DUODENALE", "ULCERA GASTRICA", "ULCERA PEPTICA",
  "UNGHIA INCARNITA", "URETRITE", "USTIONE", "UVEITE"
];

export const CONDITIONS_V = [
  "VAGINITE", "VAGINOSI BATTERICA", "VAIOLO", "VARICELLA", "VARICI ESOFAGEE",
  "VARICOCELE", "VENE VARICOSE", "VERRUCHE", "VESCICA NEUROLOGICA",
  "VIRUS ZIKA", "VITILIGINE"
];

export const CONDITIONS_Z = [
  "ZAFFAMENTO", "ZAHN (MALATTIA DI)", "ZIEVE (SINDROME DI)", "ZIGOMICOSI",
  "ZOANTROPIA"
];