export const CONDITIONS_A = [
  "ACALASIA", "ACETONEMIA", "ACIDOSI METABOLICA", "ACNE", "ACONDROPLASIA",
  "ACROMEGALIA", "ADENOIDI IPERTROFICHE", "ADENOIDITE", "AIDS", "ALBINISMO",
  "ALCOLISMO", "ALGODISTROFIA", "ALLERGIA ALIMENTARE", "ALLERGIA AL NICHEL e SNAS",
  "ALLERGIA AL LATTOSIO", "ALLERGIA DA CONTATTO", "ALLERGIE RESPIRATORIE",
  "ALLUCE VALGO", "ALOPECIA AREATA", "AMBLIOPIA", "AMEBIASI", "AMILOIDOSI",
  "ANAFILASSI", "ANEMIA", "ANEMIA DI FANCONI", "ANEMIA EMOLITICA",
  "ANEURISMA AORTICO", "ANEURISMA CEREBRALE", "ANGINA ADDOMINALE",
  "ANGINA INSTABILE", "ANGINA PECTORIS", "ANGIODISPLASIA", "ANGIOMA",
  "ANISAKIASI", "ANORESSIA", "ANSIA", "ANTRACE", "APNEA NOTTURNA",
  "APPENDICITE", "ARRESTO CARDIACO", "ARTERITE A CELLULE GIGANTI", "ARTRITE",
  "ARTRITE GOTTOSA", "ARTRITE IDIOPATICA GIOVANILE", "ARTRITE PSORIASICA",
  "ARTRITE REATTIVA", "ARTRITE REUMATOIDE", "ARTROSI", "ARTROSI DELLE MANI",
  "ARTROSI CERVICALE", "ASBESTOSI", "ASCESSO GENGIVALE", "ASCESSO PERIANALE",
  "ASCESSO POLMONARE", "ASMA", "ASPERGILLOSI", "ASTIGMATISMO", "ATEROSCLEROSI",
  "ATRESIA ESOFAGEA", "ATROFIA MUSCOLARE SPINALE", "ATTACCO DI ANSIA",
  "ATTACCO DI PANICO", "ATTACCO ISCHEMICO TRANSITORIO", "AUTISMO"
];

export const CONDITIONS_B = [
  "BABESIOSI", "BALANOPOSTITE", "BERIBERI", "BINGE DRINKING", "BLEFARITE",
  "BORSITE", "BOTULISMO", "BPCO", "BRONCHIECTASIE", "BRONCHIOLITE",
  "BRONCHITE", "BRUCELLOSI", "BRUXISMO", "BULIMIA"
];

export const CONDITIONS_C = [
  "CALAZIO", "CALCOLI AL FEGATO", "CALCOLI ALLA CISTIFELLEA", "CALCOLI RENALI",
  "CALCOLI TONSILLARI", "CALCOLOSI SALIVARE", "CALCOLOSI RENALE",
  "CANCRO AL COLLO DELL'UTERO (TUMORE)", "CANCRO AL COLON (TUMORE)",
  "CANCRO AL SENO (TUMORE)", "CANCRO ALLA PROSTATA (TUMORE)",
  "CANCRO ALL'ENDOMETRIO (TUMORE)", "CANCRO DELLA VESCICA (TUMORE)", "CANCROIDE",
  "CANDIDA", "CARCINOMA BASO-CELLULARE (BASALIOMA)",
  "CARCINOMA DELLA CERVICE UTERINA", "CARCINOMA SQUAMO - CELLULARE", "CARIE",
  "CARATATTA", "CEFALEA", "CELIACHIA", "CELLULITE", "CELLULITE INFETTIVA",
  "CERVICITE", "CHELOIDE", "CHERATITE DA HERPES SIMPLEX", "CHERATOCONO",
  "CHERATOSI ATTINICA", "CHETOACIDOSI ALCOLICA", "CHETOACIDOSI DIABETICA",
  "CHIKUNGUNYA", "CINETOSI", "CIRROSI BILIARE", "CIRROSI EPATICA",
  "CISTI DERMOIDE", "CISTI DI BAKER", "CISTI DI BARTOLINI", "CISTI OVARICA",
  "CISTICERCOSI", "CISTINURIA", "CISTITE", "CISTITE INTERSTIZIALE",
  "CISTOPIELITE", "CITOMEGALOVIRUS", "CLAMIDIA", "CLAUDICATIO INTERMITTENS",
  "COAGULAZIONE INTRAVASCOLARE DISSEMINATA", "COGGIGODINIA",
  "COLANGIOCARCINOMA", "COLANGITE SCLEROSANTE", "COLECISTITE",
  "COLECISTITE ALITIASICA", "COLELITIASI o CALCOLI BILIARI",
  "COLERA", "COLICA RENALE", "COLITE", "COLITE ISCHEMICA", "COLITE SPASTICA",
  "COLITE ULCEROSA", "COLPO DELLA STREGA", "COLPO DI CALORE",
  "COLPO DI FRUSTA CERVICALE", "CONDILOMA", "CONDROCALCINOSI", "CONDROMA",
  "CONDROMALACIA", "CONDROSARCOMA", "CONGELAMENTO", "CONGESTIONE DIGESTIVA",
  "CONGIUNTIVITE", "CONTRATTURA MUSCOLARE", "CORONOPATIA",
  "CORPO LUTEO EMORRAGICO", "COUPEROSE", "COVID 19 (CORONAVIRUS)",
  "CRIOGLOBULINEMIA", "CRIPTOCOCCOSI", "CROUP", "CUORE POLMONARE"
];

export const CONDITIONS_D = [
  "DACRIOCISTITE", "DEGENERAZIONE MACULARE SENILE", "DEMENZA SENILE",
  "DEMENZA VASCOLARE", "DENGUE", "DEPRESSIONE", "DEPRESSIONE POST PARTUM",
  "DERMATITE", "DERMATITE ATOPICA", "DERMATITE DA PANNOLINO",
  "DERMATITE PERIORALE", "DERMATITE SEBORROICA", "DERMATOFIBROMA",
  "DERMATOFITOSI", "DIABETE", "DIABETE GESTAZIONALE", "DIABETE INSIPIDO",
  "DIARREA DEL VIAGGIATORE", "DIFETTO INTERATRIALE", "DIFTERITE", "DISIDROSI",
  "DISLESSIA", "DISLIPIDEMIE", "DISPRASSIA", "DISTACCO DI RETINA", "DISTIMIA",
  "DISTORSIONE", "DISTORSIONE DELLA CAVIGLIA", "DISTRESS RESPIRATORIO",
  "DISTROFIA DI DUCHENNE", "DISTURBI DELLA COAGULAZIONE", "DISTURBO BIPOLARE",
  "DISTURBO CICLOTIMICO", "DISTURBO DA ALIMENTAZIONE INCONTROLLATA",
  "DISTURBO DI PERSONALITA' BORDERLINE", "DISTURBO EVITANTE DI PERSONALITA'",
  "DISTURBO NARCISISTICO DI PERSONALITA'", "DISTURBO OSSESSIVO COMPULSIVO",
  "DISTURBO POST TRAUMATICO DA STRESS", "DITO A SCATTO", "DIVERTICOLI ESOFAGEI",
  "DIVERTICOLITE", "DIVERTICOLO DI MECKEL", "DIVERTICOLO DI ZENKER",
  "DIVERTICOLOSI", "DREPANOCITOSI", "DUODENITE"
];
