
name: Generate Conditions Sitemaps

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  workflow_dispatch:  # Allow manual execution

jobs:
  generate-sitemaps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Supabase
        run: npm install @supabase/supabase-js
      
      - name: Create directories
        run: |
          mkdir -p public
          mkdir -p public/sitemaps
          touch public/sitemap-index.xml
      
      - name: Verify secrets
        run: |
          if [ -z "${{ secrets.SUPABASE_URL }}" ]; then
            echo "SUPABASE_URL is not set"
            exit 1
          fi
          if [ -z "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ]; then
            echo "SUPABASE_SERVICE_ROLE_KEY is not set"
            exit 1
          fi
          echo "Secrets are configured correctly"
      
      - name: Generate conditions sitemaps
        run: node scripts/generateConditionsSitemap.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      
      - name: List generated files
        run: |
          echo "Generated sitemap files:"
          ls -la public/sitemaps/
          cat public/sitemap-index.xml
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/sitemaps/ public/sitemap-index.xml
          git diff --staged --quiet || git commit -m "Update condition sitemaps [skip ci]"
          git push || echo "No changes to push"
