
name: Generate Sitemaps

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  generate-sitemaps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Supabase
        run: npm install @supabase/supabase-js
      
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.SUPABASE_URL }}" ]; then
            echo "SUPABASE_URL is not set"
            exit 1
          fi
          if [ -z "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ]; then
            echo "SUPABASE_SERVICE_ROLE_KEY is not set"
            exit 1
          fi
          echo "Both secrets are available"
      
      - name: Create basic sitemap
        run: |
          mkdir -p public
          cat > public/sitemap-reviews-1.xml << 'EOL'
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://stomale.info/patologia/allergie/esperienza/1-la-mia-esperienza-con-allergia-ai-pollini</loc>
              <changefreq>monthly</changefreq>
              <priority>0.6</priority>
            </url>
          </urlset>
          EOL
          
          cat > public/sitemap.xml << 'EOL'
          <?xml version="1.0" encoding="UTF-8"?>
          <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <sitemap>
              <loc>https://stomale.info/sitemap-reviews-1.xml</loc>
              <lastmod>2024-04-01</lastmod>
            </sitemap>
          </sitemapindex>
          EOL
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/sitemap*.xml
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update sitemaps [skip ci]"
            git push
          fi
