
name: Generate Sitemaps

on:
  schedule:
    - cron: '0 0 * * 0'  # Esegui ogni domenica a mezzanotte
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  generate-sitemaps:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Aggiungiamo permessi espliciti per scrivere nel repository
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install @supabase/supabase-js
        
      - name: Debug Environment
        run: |
          echo "Working directory: $(pwd)"
          echo "Directory contents: $(ls -la)"
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          
      - name: Generate sitemaps
        run: node scripts/generateSitemaps.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        
      - name: List generated files
        run: |
          echo "Public directory contents:"
          ls -la public/
          
      - name: Commit and push if changes exist
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update sitemaps [skip ci]"
            git push
          fi
